name: Check Dependencies
description: Check dependencies of a project and create issues if that project has out of date dependencies.
inputs:
  repository:
    description: 'repository to check'
    required: false
    default: '.'
  config_path:
    description: 'path in repo containing config file'
    required: false
    default: '.github/depcheck.yml'
  dry_run:
    description: 'when true, only print outdated dependencies in output'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
