name: Check Dependencies
description: Check dependencies of a project and create issues if that project has out of date dependencies.
inputs:
  repository:
    description: 'repository to check'
    required: false
    default: '.'
  config-path:
    description: 'path in repo containing config file'
    required: false
    default: '.github/depcheck.yml'
  dry-run:
    description: 'when true, only print outdated dependencies in output'
    required: false
  github-token:
    description: 'token to use for authenticating requests to open issues'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
